version: '3.8'

services:
  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    ports:
      - "3306:3306"

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  backend:
    build: ./backend
    ports:
      - "8001:8001"
      - "8002:8002" 
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
      - "8006:8006"
    environment:
      - APP_ENV=development
      - DB_HOST=mysql
      - DB_USER=pavitra_user
      - DB_PASSWORD=user123
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    command: >
      sh -c "pip install -r requirements.txt &&
             python production_manager.py"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:

networks:
  pavitra-network:
    driver: bridge
