services:
  mysql:
    image: mysql:8.0
    container_name: pavitra-mysql
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=512M
      - --innodb-log-file-size=256M
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-site-settings.sql:/docker-entrypoint-initdb.d/02_settings.sql
      - ./scripts/add_roles_permissions.sql:/docker-entrypoint-initdb.d/03_roles.sql
      - ./scripts/add_notification_table.sql:/docker-entrypoint-initdb.d/04_notifications.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
