INSERT INTO site_settings (setting_key, setting_value, setting_type) VALUES
('app_name', 'Pavitra Trading', 'string'),
('app_description', 'Your trusted online shopping destination in India', 'string'),
('log_level', 'INFO', 'string'),
('maintenance_mode', 'false', 'boolean'),
('debug_mode', 'false', 'boolean'),
('cors_origins', '["http://localhost:3000", "http://localhost:3001"]', 'json'),
('default_currency', 'INR', 'string'),
('currency_symbol', '₹', 'string'),
('supported_currencies', '["INR", "USD", "GBP", "EUR"]', 'json'),
('default_country', 'IN', 'string'),
('default_gst_rate', '18.00', 'number'),
('enable_guest_checkout', 'true', 'boolean'),
('enable_reviews', 'true', 'boolean'),
('enable_wishlist', 'true', 'boolean'),
('min_order_amount', '0.00', 'number'),
('free_shipping_min_amount', '500.00', 'number'),
('max_upload_size', '5242880', 'number'),
('allowed_file_types', '["jpg", "jpeg", "png", "gif", "webp"]', 'json'),
('rate_limit_requests', '100', 'number'),
('rate_limit_window', '900', 'number'),
('redis_host', 'localhost', 'string'),
('redis_port', '6379', 'number'),
('redis_password', '', 'string'),
('redis_db', '0', 'number'),
('rabbitmq_host', 'localhost', 'string'),
('rabbitmq_port', '5672', 'number'),
('rabbitmq_user', 'guest', 'string'),
('rabbitmq_password', 'guest', 'string'),
('smtp_host', 'smtp.gmail.com', 'string'),
('smtp_port', '587', 'number'),
('smtp_username', '', 'string'),
('smtp_password', '', 'string'),
('email_from', 'noreply@pavitra-trading.com', 'string'),
('razorpay_test_mode', 'true', 'boolean'),
('stripe_test_mode', 'true', 'boolean'),
('email_notifications', 'true', 'boolean'),
('sms_notifications', 'true', 'boolean')
ON DUPLICATE KEY UPDATE
setting_value = VALUES(setting_value),
setting_type = VALUES(setting_type);

SELECT 'Site settings initialized successfully!' as status;